Update README.md
EpicGames/ThirdParty pull request #6
Opened 2018-08-20 18:12 UTC by VisaBuy

2018-08-29 19:05 UTC, zwavy310 approved these changes

2018-09-02 23:15 UTC, Kampfkarren requested changes
Hmm

2018-09-02 23:15 UTC, chesse20 approved these changes
yea

2018-09-02 23:15 UTC, chesse20 commented on README.md
> +Draze BRN
wow

2018-09-17 16:50 UTC, billygoatj commented on README.md
> +Draze BRN
Looks good

2018-10-06 17:23 UTC, Kpryz75 approved these changes

2018-10-16 01:20 UTC, Kenner-G requested changes
[SPAM]

Do not approve.

2018-12-15 15:52 UTC, RDIL requested changes
nah

2018-12-15 17:57 UTC, chesse20 requested changes

2018-12-15 17:57 UTC, chesse20 commented on README.md
> +DrazeXMK
add my name here to

2019-01-13 18:36 UTC, jondamico1 approved these changes

2019-04-07 04:58 UTC, stephensjames177 approved these changes

2019-05-15 17:29 UTC, ghost approved these changes

2019-11-20 18:45 UTC, jgreever requested changes
[SPAM]

This will be rejected as no needed/useful changes were done. Adding names for the sake of it ruins the idea of this being an open organization. Time to close the doors to the public if this behavior keeps up.

Add useful/needed changes only, please do not add spam to this repo like this again.

2020-10-31 10:37 UTC, ni3nh commented on README.md
> +DrazeXMK
n

2020-10-31 22:06 UTC, Kampfkarren commented
[SPAM]

This will be rejected as no needed/useful changes were done. Adding names for the sake of it ruins the idea of this being an open organization. Time to close the doors to the public if this behavior keeps up.

Add useful/needed changes only, please do not add spam to this repo like this again.

2021-04-24 03:59 UTC, bl1mp commented
> [SPAM]
> 
> This will be rejected as no needed/useful changes were done. Adding names for the sake of it ruins the idea of this being an open organization. Time to close the doors to the public if this behavior keeps up.
> 
> Add useful/needed changes only, please do not add spam to this repo like this again.

agreed.

2021-04-26 01:15 UTC, chesse20 commented
> 
> 
> > [SPAM]
> > This will be rejected as no needed/useful changes were done. Adding names for the sake of it ruins the idea of this being an open organization. Time to close the doors to the public if this behavior keeps up.
> > Add useful/needed changes only, please do not add spam to this repo like this again.
> 
> agreed.

What

2021-06-02 19:04 UTC, Messhias requested changes
Please remove your names, there's no reason to open a PR just to add your names, what's the use this for open source software?

2021-06-02 19:04 UTC, Messhias commented on README.md
> +Draze BRN
Remove names, this isn't useful for organizations and open source. Please be aware to follow the culture.

2021-06-02 19:04 UTC, Messhias commented on README.md
> +HydreKayzi
Remove names, this isn't useful for organizations and open source. Please be aware to follow the culture.

2021-06-02 19:04 UTC, Messhias commented on README.md
> +DrazeXMK
Remove names, this isn't useful for organizations and open source. Please be aware to follow the culture.

2021-06-02 20:50 UTC, chesse20 commented
can they add my name too

2021-06-02 20:58 UTC, Messhias commented
No.

On Wed, Jun 2, 2021, 21:51 chesse20 ***@***.***> wrote:

> can they add my name too
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/EpicGames/ThirdParty/pull/6#issuecomment-853373847>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI3QQ4FJSWNPTIQC4EBIK3TQ2KTRANCNFSM4FQR4BRA>
> .
>

2022-06-05 21:08 UTC, closed without merging